// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZJaoM6Ra_QHhfQNHiHwc6JAtpfEfD3Ug',
    appId: '1:1014365213590:web:464ac1210995fed5c883b7',
    messagingSenderId: '1014365213590',
    projectId: 'yade-app',
    authDomain: 'yade-app.firebaseapp.com',
    storageBucket: 'yade-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDUVRRtw0DfqpcSF3h7wFbR4B_y15bSQ4',
    appId: '1:1014365213590:android:b23ebc90ae79bc44c883b7',
    messagingSenderId: '1014365213590',
    projectId: 'yade-app',
    storageBucket: 'yade-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrE53QXOBX2dJ6axIUOtciccM4_Re1swY',
    appId: '1:1014365213590:ios:f743a36a933a3a2ac883b7',
    messagingSenderId: '1014365213590',
    projectId: 'yade-app',
    storageBucket: 'yade-app.firebasestorage.app',
    iosBundleId: 'com.example.yadeBus',
  );
}
